param(
    [Parameter(Mandatory = $true)]
    [string]$UpstreamRoot
)

$ErrorActionPreference = 'Stop'

function Replace-Exact {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Old,
        [Parameter(Mandatory = $true)][string]$New
    )

    $fullPath = Join-Path $UpstreamRoot $Path
    if (-not (Test-Path $fullPath)) {
        throw "Missing upstream file: $Path"
    }

    $text = [IO.File]::ReadAllText($fullPath) -replace "`r`n", "`n"
    $oldNormalized = $Old -replace "`r`n", "`n"
    $newNormalized = $New -replace "`r`n", "`n"
    if (-not $text.Contains($oldNormalized)) {
        throw "Anchor not found in $Path`n--- anchor ---`n$oldNormalized"
    }

    [IO.File]::WriteAllText(
        $fullPath,
        $text.Replace($oldNormalized, $newNormalized),
        [Text.UTF8Encoding]::new($false))
}

# Scriban 7.2.x targets netstandard2.0 but consumes System.Text.Json 10.x. The pinned upstream
# Common project and the legacy net472 Coop project still force 9.0.2 into the deploy directory,
# producing a real back-level runtime dependency. Align the staged KaiTOR build on the minimum
# dependency set required by System.Text.Json 10.0.8. These packages all support net462/netstandard2.0
# and therefore remain compatible with Bannerlord's net472 module host.
Replace-Exact 'source/Common/Common.csproj' `
    '<PackageReference Include="System.Text.Json" Version="9.0.2" />' `
    '<PackageReference Include="System.Text.Json" Version="10.0.8" />'

$packageUpgrades = [ordered]@{
    'Microsoft.Bcl.AsyncInterfaces' = @('9.0.2', '10.0.8')
    'System.Buffers' = @('4.6.0', '4.6.1')
    'System.IO.Pipelines' = @('9.0.2', '10.0.8')
    'System.Memory' = @('4.6.0', '4.6.3')
    'System.Runtime.CompilerServices.Unsafe' = @('6.1.0', '6.1.2')
    'System.Text.Encodings.Web' = @('9.0.2', '10.0.8')
    'System.Text.Json' = @('9.0.2', '10.0.8')
    'System.Threading.Tasks.Extensions' = @('4.6.0', '4.6.3')
    'System.ValueTuple' = @('4.5.0', '4.6.2')
}

foreach ($name in $packageUpgrades.Keys) {
    $from = $packageUpgrades[$name][0]
    $to = $packageUpgrades[$name][1]
    $oldPackage = '<package id="{0}" version="{1}" targetFramework="net472" />' -f $name, $from
    $newPackage = '<package id="{0}" version="{1}" targetFramework="net472" />' -f $name, $to
    Replace-Exact 'source/Coop/packages.config' $oldPackage $newPackage
}

# Legacy csproj references include exact assembly identities generated by old NuGet tooling.
# Drop version metadata for the aligned BCL references and point their HintPaths at the upgraded
# packages; MSBuild will resolve the actual strong-name identity from each DLL.
$legacyReferences = @(
    @('Microsoft.Bcl.AsyncInterfaces', '9.0.2', '10.0.8', 'net462'),
    @('System.Buffers', '4.6.0', '4.6.1', 'net462'),
    @('System.IO.Pipelines', '9.0.2', '10.0.8', 'net462'),
    @('System.Memory', '4.6.0', '4.6.3', 'net462'),
    @('System.Runtime.CompilerServices.Unsafe', '6.1.0', '6.1.2', 'net462'),
    @('System.Text.Encodings.Web', '9.0.2', '10.0.8', 'net462'),
    @('System.Text.Json', '9.0.2', '10.0.8', 'net462'),
    @('System.Threading.Tasks.Extensions', '4.6.0', '4.6.3', 'net462'),
    @('System.ValueTuple', '4.5.0', '4.6.2', 'net462')
)

$coopCsproj = Join-Path $UpstreamRoot 'source/Coop/Coop.csproj'
$text = [IO.File]::ReadAllText($coopCsproj) -replace "`r`n", "`n"
foreach ($reference in $legacyReferences) {
    $name = $reference[0]
    $from = $reference[1]
    $to = $reference[2]
    $tfm = $reference[3]

    $includePattern = '<Reference Include="{0}, Version=[^"]+">' -f [regex]::Escape($name)
    $replacementInclude = '<Reference Include="{0}">' -f $name
    $updated = [regex]::Replace($text, $includePattern, $replacementInclude, 1)
    if ($updated -eq $text) {
        throw "Legacy Reference anchor not found for $name in source/Coop/Coop.csproj"
    }
    $text = $updated

    $oldHint = "..\packages\$name.$from\lib\"
    if (-not $text.Contains($oldHint)) {
        throw "Legacy HintPath anchor not found for $name $from in source/Coop/Coop.csproj"
    }
    $text = $text.Replace($oldHint, "..\packages\$name.$to\lib\")

    # ValueTuple historically used net47; the aligned package ships a net462 asset as well.
    if ($name -eq 'System.ValueTuple') {
        $text = $text.Replace("System.ValueTuple.$to\lib\net47\System.ValueTuple.dll", "System.ValueTuple.$to\lib\$tfm\System.ValueTuple.dll")
    }
}
[IO.File]::WriteAllText($coopCsproj, $text, [Text.UTF8Encoding]::new($false))

Write-Host 'Aligned KaiTOR managed dependency graph on System.Text.Json 10.0.8-compatible packages.'
